dev:
  build: .
  command: bin/rails server --port 3000 --binding 0.0.0.0
  ports:
    - '3000:3000'
  volumes:
    - .:/var/www
  links:
    - db
    - memcached
    - redis
    - elasticsearch
    - nginx
  environment:
    RAILS_ENV: development
  
test: 
  build: .
  command: bin/rspec
  volumes:
    - .:/var/www
  links:
    - db
  environment:
    RAILS_ENV: test

db:
  image: postgres:9.4
  environment:
    POSTGRES_USER: 'mereveilleuse'
    POSTGRES_PASSWORD: 'mereveilleuse'

memcached:
  image: sameersbn/memcached:latest
  environment:
    CACHE_SIZE: '64'

redis: 
  image: redis

elasticsearch:
  image: elasticsearch

nginx: 
  image: surzycki/nginx.stable
  ports:
    - '80:80'
