dev:
  build: .
  command: bin/rails server --port 3000 --binding 0.0.0.0
  
  volumes:
    - .:/var/www
  links:
    - db
    - memcached
    - redis
    - elasticsearch
  environment:
    RAILS_ENV: development  
  hostname: appfacebook_dev
  expose: 
    - '3000'
  ports:
    - '80:3000'

test: 
  build: .
  command: bin/rspec
  volumes:
    - .:/var/www
  links:
    - db
  environment:
    RAILS_ENV: test

db:
  image: postgres:9.4
  environment:
    POSTGRES_USER: 'mereveilleuse'
    POSTGRES_PASSWORD: 'mereveilleuse'

memcached:
  image: sameersbn/memcached:latest
  environment:
    CACHE_SIZE: '64'

redis: 
  image: redis

elasticsearch:
  image: elasticsearch

nginx: 
  image: quay.io/surzycki/nginx.stable-dev
  ports:
    - '443:443'
  external_links:
    - appfacebook_dev_run_134:dev  
